# Generated by Django 4.0.2 on 2022-03-10 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('points_per_tally', models.PositiveSmallIntegerField(default=1, verbose_name='points gained per tally')),
                ('is_xp', models.BooleanField(default=True, help_text='Select if this is for xp; leave blank if for custom points')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('general', models.CharField(blank=True, help_text='your name', max_length=100, null=True)),
                ('battles', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('battles_won', models.PositiveSmallIntegerField(default=0)),
                ('custom_points', models.PositiveSmallIntegerField(default=0)),
                ('custom_points_name', models.CharField(blank=True, help_text='e.g. virulence points', max_length=100)),
                ('supply_limit', models.PositiveSmallIntegerField(default=0)),
                ('supply_used', models.PositiveSmallIntegerField(default=0)),
                ('total_rp', models.PositiveSmallIntegerField(default=0, verbose_name='Total requisition')),
                ('spent_rp', models.PositiveSmallIntegerField(default=0, verbose_name='Spent requisition')),
                ('crusade_faction', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='army', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Armies',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='short description i.e. "5 intercessors', max_length=100)),
                ('power', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('crusade_points', models.PositiveSmallIntegerField(default=0)),
                ('xp', models.PositiveSmallIntegerField(default=0)),
                ('battles_fought', models.PositiveSmallIntegerField(default=0)),
                ('battles_survived', models.PositiveSmallIntegerField(default=0)),
                ('marked_for_greatness', models.PositiveSmallIntegerField(default=0, help_text='Number of times marked for greatness')),
                ('misc_xp_gain_loss', models.PositiveSmallIntegerField(default=0, help_text='Miscellaneous XP gain or losses')),
                ('battle_honours', models.CharField(blank=True, max_length=300, null=True)),
                ('battle_scars', models.CharField(blank=True, max_length=300, null=True)),
                ('equipment', models.CharField(blank=True, max_length=300, null=True)),
                ('warlord_trait', models.CharField(blank=True, max_length=300, null=True)),
                ('relic', models.CharField(blank=True, max_length=300, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='order_of_battle.army')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('range', models.CharField(default=0, max_length=10)),
                ('type', models.CharField(default=0, max_length=20)),
                ('strength', models.CharField(max_length=5, verbose_name='S')),
                ('armor_piercing', models.CharField(max_length=2, verbose_name='AP')),
                ('damage', models.CharField(max_length=10, verbose_name='D')),
                ('description', models.CharField(help_text='e.g. blast, poison weapon 4+', max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='order_of_battle.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
                'ordering': ('unit', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('movement', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='M')),
                ('weapon_skill', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='WS')),
                ('ballistic_skill', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='BS')),
                ('strength', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='S')),
                ('toughness', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='T')),
                ('wounds', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='W')),
                ('attacks', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='A')),
                ('leadership', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Ld')),
                ('sv', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Sv')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='order_of_battle.unit', verbose_name='unit')),
            ],
        ),
    ]
