# Generated by Django 4.0.2 on 2022-02-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_of_battle',
            name='battles_fought',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_of_battle',
            name='battles_survived',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_of_battle',
            name='crusade_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_of_battle',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_of_battle',
            name='power',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
