# Generated by Django 4.0.2 on 2022-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0008_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='order_of_battle',
            field=models.ManyToManyField(related_name='agendas', to='order_of_battle.Unit'),
        ),
    ]
