# Generated by Django 4.0.2 on 2022-03-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0009_alter_agenda_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='order_of_battle',
            new_name='units',
        ),
    ]
