# Generated by Django 4.0.2 on 2022-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0010_rename_unit_agenda_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
