# Generated by Django 4.0.2 on 2022-03-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0011_unit_xp_delete_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movement', models.CharField(max_length=5, verbose_name='M')),
                ('weapon_skill', models.CharField(max_length=5, verbose_name='WS')),
                ('ballistic_skill', models.PositiveSmallIntegerField(default=0, verbose_name='BS')),
                ('strength', models.PositiveSmallIntegerField(default=0, verbose_name='S')),
                ('toughness', models.PositiveSmallIntegerField(default=0, verbose_name='T')),
                ('wounds', models.PositiveSmallIntegerField(default=0, verbose_name='W')),
                ('attacks', models.PositiveSmallIntegerField(default=0, verbose_name='A')),
                ('leadership', models.PositiveSmallIntegerField(default=0, verbose_name='Ld')),
                ('save', models.PositiveSmallIntegerField(default=0, verbose_name='Sv')),
                ('order_of_battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='order_of_battle.unit', verbose_name='order_of_battle')),
            ],
        ),
    ]
