# Generated by Django 4.0.2 on 2022-03-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0018_unit_battle_honours_unit_battle_scars_unit_equipment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ('unit', 'name'), 'verbose_name': 'Weapon', 'verbose_name_plural': 'Weapons'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order_of_battle',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='order_of_battle',
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='order_of_battle.unit', verbose_name='unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='order_of_battle.unit', verbose_name='order_of_battle'),
            preserve_default=False,
        ),
    ]
