# Generated by Django 4.0.2 on 2022-03-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0020_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('battles', models.PositiveSmallIntegerField(default=0)),
                ('battles_won', models.PositiveSmallIntegerField(default=0)),
                ('custom_points', models.PositiveSmallIntegerField(default=0)),
                ('custom_points_name', models.CharField(blank=True, help_text='e.g. virulence points', max_length=100)),
                ('supply_limit', models.PositiveSmallIntegerField(default=0)),
                ('supply_used', models.PositiveSmallIntegerField(default=0)),
                ('total_rp', models.PositiveSmallIntegerField(default=0, verbose_name='Total requisition')),
                ('spent_rp', models.PositiveSmallIntegerField(default=0, verbose_name='Spent requisition')),
                ('crusade_faction', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='order_of_battle.unit', verbose_name='unit'),
        ),
    ]
