# Generated by Django 4.0.2 on 2022-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0021_army_alter_weapon_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='army',
            options={'verbose_name_plural': 'Armies'},
        ),
        migrations.AddField(
            model_name='army',
            name='general',
            field=models.CharField(blank=True, help_text='your name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='army',
            name='crusade_faction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
