# Generated by Django 4.0.2 on 2022-03-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_of_battle', '0022_alter_army_options_army_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='army',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='order_of_battle.army'),
            preserve_default=False,
        ),
    ]
