# Generated by Django 4.0.2 on 2022-02-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_battles_fought_unit_battles_survived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Optional; e.g. "Battle of Vortrex Divide', max_length=200, null=True)),
                ('enemy', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='battles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unit.battle'),
            preserve_default=False,
        ),
    ]
