# Generated by Django 4.0.2 on 2022-03-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0005_alter_unit_battles_alter_unit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('range', models.CharField(default=0, max_length=10)),
                ('type', models.CharField(default=0, max_length=20)),
                ('strength', models.CharField(max_length=5, verbose_name='S')),
                ('armor_piercing', models.CharField(max_length=2, verbose_name='AP')),
                ('damage', models.CharField(max_length=10, verbose_name='D')),
                ('description', models.CharField(help_text='e.g. blast, poison weapon 4+', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Battle',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='battles',
        ),
        migrations.AddField(
            model_name='unit',
            name='marked_for_greatness',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times marked for greatness'),
        ),
        migrations.AddField(
            model_name='unit',
            name='misc_xp_gain_loss',
            field=models.PositiveSmallIntegerField(default=0, help_text='Miscellaneous XP gain or losses'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.unit'),
        ),
    ]
