# Generated by Django 4.0.2 on 2022-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0014_alter_profile_movement_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attacks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ballistic_skill',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='BS'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='leadership',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Ld'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movement',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='save',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Sv'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='strength',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='toughness',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='T'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weapon_skill',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='WS'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wounds',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='W'),
        ),
    ]
