# Generated by Django 4.0.2 on 2022-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0016_rename_save_profile_sv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
